BEGIN;

-- A publication can require hundreds of risk-tiered object reviews. Preserve
-- the existing per-object authority checks while allowing one reviewer to
-- submit a bounded, explicit set atomically. One invalid decision aborts the
-- complete batch; no approval is inferred or generated by the database.

-- Repair the original single-review writer before composing the batch API on
-- top of it. Migration 0101 declared the notes target column but omitted the
-- corresponding value, so the first real review attempt failed closed with an
-- INSERT arity error. Keep this repair in a new migration because 0101 is
-- already checksummed and applied in deployed environments.
CREATE OR REPLACE FUNCTION public.albert_semantic_v2_record_review(
  p_review_id text,
  p_draft_id text,
  p_expected_revision integer,
  p_object_id text,
  p_risk_tier text,
  p_disposition text,
  p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path=pg_catalog,public,control_plane
AS $$
DECLARE
  v_revision integer;
  v_manifest jsonb;
  v_required_tier text;
BEGIN
  IF NOT control_plane.is_internal_operator() THEN
    RAISE EXCEPTION 'internal operator access is required' USING ERRCODE='42501';
  END IF;
  SELECT revision,manifest INTO v_revision,v_manifest
  FROM control_plane.semantic_v2_drafts
  WHERE draft_id=p_draft_id;
  IF v_revision IS NULL THEN
    RAISE EXCEPTION 'semantic draft not found' USING ERRCODE='P0002';
  END IF;
  IF v_revision<>p_expected_revision THEN
    RAISE EXCEPTION 'semantic draft revision conflict' USING ERRCODE='40001';
  END IF;
  SELECT CASE
    WHEN object_type='measure' AND object_value->>'semanticState' IN ('verified','derived')
      THEN object_value->>'riskTier'
    WHEN object_type='relationship' AND object_value->>'semanticState' IN ('verified','derived')
      THEN 'tier_1'
    WHEN object_type='topic' AND object_value->>'layer'='composite'
      AND object_value->>'semanticState' IN ('verified','derived') THEN 'tier_1'
    WHEN object_type='field' AND (
      COALESCE((object_value->>'pii')::boolean,false)
      OR object_value->>'disposition'='sensitive_metadata'
    ) THEN 'tier_1'
    ELSE 'tier_3'
  END INTO v_required_tier
  FROM (
    SELECT 'measure' AS object_type,value AS object_value
    FROM jsonb_array_elements(v_manifest->'measures')
    UNION ALL
    SELECT 'relationship',value
    FROM jsonb_array_elements(v_manifest->'relationships')
    UNION ALL
    SELECT 'topic',value
    FROM jsonb_array_elements(v_manifest->'topics')
    UNION ALL
    SELECT 'field',field_value
    FROM jsonb_array_elements(v_manifest->'sourceObjects') source_value
    CROSS JOIN LATERAL jsonb_array_elements(source_value->'fields') field_value
  ) reviewable
  WHERE object_value->>'id'=p_object_id
  LIMIT 1;
  IF v_required_tier IS NULL THEN
    RAISE EXCEPTION 'semantic object is not reviewable' USING ERRCODE='22023';
  END IF;
  IF p_risk_tier<>v_required_tier THEN
    RAISE EXCEPTION 'review tier does not match the semantic contract' USING ERRCODE='22023';
  END IF;
  IF (v_required_tier IN ('tier_1','tier_2') AND p_disposition='sampled')
     OR (v_required_tier='tier_3' AND p_disposition='approved') THEN
    RAISE EXCEPTION 'review disposition does not match the semantic risk tier' USING ERRCODE='22023';
  END IF;
  INSERT INTO control_plane.semantic_v2_object_reviews(
    review_id,draft_id,draft_revision,object_id,risk_tier,disposition,reviewer_id,notes
  ) VALUES (
    p_review_id,p_draft_id,p_expected_revision,p_object_id,p_risk_tier,
    p_disposition,extensions.albert_auth_uid(),p_notes
  )
  ON CONFLICT (draft_id,draft_revision,object_id,reviewer_id)
  DO UPDATE SET
    risk_tier=excluded.risk_tier,
    disposition=excluded.disposition,
    notes=excluded.notes,
    created_at=now();
  RETURN jsonb_build_object(
    'reviewId',p_review_id,
    'draftId',p_draft_id,
    'revision',p_expected_revision,
    'objectId',p_object_id,
    'disposition',p_disposition
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.albert_semantic_v2_record_review_batch(
  p_draft_id text,
  p_expected_revision integer,
  p_reviews jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path=pg_catalog,public,control_plane
AS $$
DECLARE
  v_review jsonb;
  v_result jsonb;
  v_results jsonb := '[]'::jsonb;
BEGIN
  IF NOT control_plane.is_internal_operator() THEN
    RAISE EXCEPTION 'internal operator access is required' USING ERRCODE='42501';
  END IF;
  IF jsonb_typeof(p_reviews)<>'array'
     OR jsonb_array_length(p_reviews) NOT BETWEEN 1 AND 100 THEN
    RAISE EXCEPTION 'semantic review batch must contain between 1 and 100 decisions'
      USING ERRCODE='22023';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reviews) item
    WHERE jsonb_typeof(item)<>'object'
       OR NOT item ?& ARRAY['reviewId','objectId','riskTier','disposition','notes']
       OR item - ARRAY['reviewId','objectId','riskTier','disposition','notes']::text[] <> '{}'::jsonb
       OR jsonb_typeof(item->'notes')<>'string'
       OR length(btrim(item->>'notes')) NOT BETWEEN 10 AND 2000
  ) THEN
    RAISE EXCEPTION 'semantic review batch decisions have an invalid shape'
      USING ERRCODE='22023';
  END IF;
  IF (
    SELECT count(*)<>count(DISTINCT item->>'objectId')
    FROM jsonb_array_elements(p_reviews) item
  ) THEN
    RAISE EXCEPTION 'a semantic object may appear only once in a review batch'
      USING ERRCODE='22023';
  END IF;

  FOR v_review IN SELECT value FROM jsonb_array_elements(p_reviews) LOOP
    v_result := public.albert_semantic_v2_record_review(
      v_review->>'reviewId',
      p_draft_id,
      p_expected_revision,
      v_review->>'objectId',
      v_review->>'riskTier',
      v_review->>'disposition',
      v_review->>'notes'
    );
    v_results := v_results || jsonb_build_array(v_result);
  END LOOP;

  RETURN jsonb_build_object(
    'draftId',p_draft_id,
    'revision',p_expected_revision,
    'recorded',jsonb_array_length(v_results),
    'reviews',v_results
  );
END;
$$;

-- The general admin-state projection is intentionally capped and can span
-- many drafts. Publication review needs the complete reviewer set for one
-- exact immutable revision so approval counts cannot be understated.
CREATE OR REPLACE FUNCTION public.albert_semantic_v2_admin_draft_reviews(
  p_draft_id text,
  p_draft_revision integer
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path=pg_catalog,public,control_plane
AS $$
DECLARE
  v_count integer;
  v_reviews jsonb;
BEGIN
  IF NOT control_plane.is_internal_operator() THEN
    RAISE EXCEPTION 'internal operator access is required' USING ERRCODE='42501';
  END IF;
  IF p_draft_id IS NULL OR length(btrim(p_draft_id))=0
     OR p_draft_revision IS NULL OR p_draft_revision<1 THEN
    RAISE EXCEPTION 'a positive draft revision is required' USING ERRCODE='22023';
  END IF;
  SELECT count(*) INTO v_count
  FROM control_plane.semantic_v2_object_reviews
  WHERE draft_id=p_draft_id AND draft_revision=p_draft_revision;
  SELECT coalesce(jsonb_agg(to_jsonb(item) ORDER BY item.object_id,item.reviewer_id),'[]'::jsonb)
  INTO v_reviews
  FROM (
    SELECT draft_id,draft_revision,object_id,risk_tier,disposition,reviewer_id,created_at
    FROM control_plane.semantic_v2_object_reviews
    WHERE draft_id=p_draft_id AND draft_revision=p_draft_revision
    ORDER BY object_id,reviewer_id
    LIMIT 5000
  ) item;
  RETURN jsonb_build_object(
    'reviews',v_reviews,
    'count',v_count,
    'truncated',v_count>5000
  );
END;
$$;

REVOKE ALL ON FUNCTION public.albert_semantic_v2_record_review_batch(
  text,integer,jsonb
) FROM PUBLIC,anon,service_role;
REVOKE ALL ON FUNCTION public.albert_semantic_v2_admin_draft_reviews(
  text,integer
) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.albert_semantic_v2_record_review_batch(
  text,integer,jsonb
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.albert_semantic_v2_admin_draft_reviews(
  text,integer
) TO authenticated;

COMMIT;
