BEGIN;

-- A publication can require hundreds of risk-tiered object reviews. Preserve
-- the existing per-object authority checks while allowing one reviewer to
-- submit a bounded, explicit set atomically. One invalid decision aborts the
-- complete batch; no approval is inferred or generated by the database.

CREATE OR REPLACE FUNCTION public.albert_semantic_v2_record_review_batch(
  p_draft_id text,
  p_expected_revision integer,
  p_reviews jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path=pg_catalog,public,control_plane
AS $$
DECLARE
  v_review jsonb;
  v_result jsonb;
  v_results jsonb := '[]'::jsonb;
BEGIN
  IF NOT control_plane.is_internal_operator() THEN
    RAISE EXCEPTION 'internal operator access is required' USING ERRCODE='42501';
  END IF;
  IF jsonb_typeof(p_reviews)<>'array'
     OR jsonb_array_length(p_reviews) NOT BETWEEN 1 AND 100 THEN
    RAISE EXCEPTION 'semantic review batch must contain between 1 and 100 decisions'
      USING ERRCODE='22023';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_reviews) item
    WHERE jsonb_typeof(item)<>'object'
       OR NOT item ?& ARRAY['reviewId','objectId','riskTier','disposition']
       OR item - ARRAY['reviewId','objectId','riskTier','disposition','notes']::text[] <> '{}'::jsonb
  ) THEN
    RAISE EXCEPTION 'semantic review batch decisions have an invalid shape'
      USING ERRCODE='22023';
  END IF;
  IF (
    SELECT count(*)<>count(DISTINCT item->>'objectId')
    FROM jsonb_array_elements(p_reviews) item
  ) THEN
    RAISE EXCEPTION 'a semantic object may appear only once in a review batch'
      USING ERRCODE='22023';
  END IF;

  FOR v_review IN SELECT value FROM jsonb_array_elements(p_reviews) LOOP
    v_result := public.albert_semantic_v2_record_review(
      v_review->>'reviewId',
      p_draft_id,
      p_expected_revision,
      v_review->>'objectId',
      v_review->>'riskTier',
      v_review->>'disposition',
      v_review->>'notes'
    );
    v_results := v_results || jsonb_build_array(v_result);
  END LOOP;

  RETURN jsonb_build_object(
    'draftId',p_draft_id,
    'revision',p_expected_revision,
    'recorded',jsonb_array_length(v_results),
    'reviews',v_results
  );
END;
$$;

-- The general admin-state projection is intentionally capped and can span
-- many drafts. Publication review needs the complete reviewer set for one
-- exact immutable revision so approval counts cannot be understated.
CREATE OR REPLACE FUNCTION public.albert_semantic_v2_admin_draft_reviews(
  p_draft_id text,
  p_draft_revision integer
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path=pg_catalog,public,control_plane
AS $$
DECLARE
  v_count integer;
  v_reviews jsonb;
BEGIN
  IF NOT control_plane.is_internal_operator() THEN
    RAISE EXCEPTION 'internal operator access is required' USING ERRCODE='42501';
  END IF;
  IF p_draft_id IS NULL OR length(btrim(p_draft_id))=0
     OR p_draft_revision IS NULL OR p_draft_revision<1 THEN
    RAISE EXCEPTION 'a positive draft revision is required' USING ERRCODE='22023';
  END IF;
  SELECT count(*) INTO v_count
  FROM control_plane.semantic_v2_object_reviews
  WHERE draft_id=p_draft_id AND draft_revision=p_draft_revision;
  SELECT coalesce(jsonb_agg(to_jsonb(item) ORDER BY item.object_id,item.reviewer_id),'[]'::jsonb)
  INTO v_reviews
  FROM (
    SELECT draft_id,draft_revision,object_id,risk_tier,disposition,reviewer_id,created_at
    FROM control_plane.semantic_v2_object_reviews
    WHERE draft_id=p_draft_id AND draft_revision=p_draft_revision
    ORDER BY object_id,reviewer_id
    LIMIT 5000
  ) item;
  RETURN jsonb_build_object(
    'reviews',v_reviews,
    'count',v_count,
    'truncated',v_count>5000
  );
END;
$$;

REVOKE ALL ON FUNCTION public.albert_semantic_v2_record_review_batch(
  text,integer,jsonb
) FROM PUBLIC,anon,service_role;
REVOKE ALL ON FUNCTION public.albert_semantic_v2_admin_draft_reviews(
  text,integer
) FROM PUBLIC,anon,service_role;
GRANT EXECUTE ON FUNCTION public.albert_semantic_v2_record_review_batch(
  text,integer,jsonb
) TO authenticated;
GRANT EXECUTE ON FUNCTION public.albert_semantic_v2_admin_draft_reviews(
  text,integer
) TO authenticated;

COMMIT;
