-- 0153: per-tenant business context document (the business context layer).
--
-- Every Albert turn is grounded in a ~400-word structured description of the
-- business: what it is, how it makes money, its scale and shape, the owner's
-- goals and vocabulary, and what each connected tool is the source of truth
-- for. The document is generated by Albert from connected-tool data (see
-- packages/albert-v3/src/context-layer), confirmed and edited by the owner in
-- the dashboard, and refreshed from data when stale — owner-locked sections
-- survive regeneration. One row per tenant plus an append-only revision log.
--
-- Access is membership-scoped through SECURITY DEFINER RPCs (same posture as
-- tenant_source_findings, 0141): every active member reads; owner/manager
-- write (generated refreshes, edits, confirmation).

BEGIN;

CREATE TABLE IF NOT EXISTS control_plane.tenant_business_context (
  tenant_id text PRIMARY KEY,
  document jsonb NOT NULL,
  rendered text NOT NULL,
  facts jsonb,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'confirmed')),
  owner_locked jsonb NOT NULL DEFAULT '[]'::jsonb,
  connectors jsonb NOT NULL DEFAULT '[]'::jsonb,
  generator_version text,
  model text,
  data_through timestamptz,
  generated_at timestamptz,
  confirmed_at timestamptz,
  confirmed_by uuid,
  revision integer NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);
ALTER TABLE control_plane.tenant_business_context ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS control_plane.tenant_business_context_revisions (
  tenant_id text NOT NULL,
  revision_id text NOT NULL DEFAULT control_plane.generate_ulid(),
  revision integer NOT NULL,
  source text NOT NULL CHECK (source IN ('generated', 'owner', 'confirmed')),
  document jsonb NOT NULL,
  rendered text NOT NULL,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, revision_id)
);
CREATE INDEX IF NOT EXISTS tenant_business_context_revisions_recent
  ON control_plane.tenant_business_context_revisions (tenant_id, created_at DESC);
ALTER TABLE control_plane.tenant_business_context_revisions ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION control_plane.business_context_row_json(ctx control_plane.tenant_business_context)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog
AS $$
  SELECT jsonb_build_object(
    'document', ctx.document,
    'rendered', ctx.rendered,
    'status', ctx.status,
    'ownerLocked', ctx.owner_locked,
    'connectors', ctx.connectors,
    'generatorVersion', ctx.generator_version,
    'model', ctx.model,
    'dataThrough', ctx.data_through,
    'generatedAt', ctx.generated_at,
    'confirmedAt', ctx.confirmed_at,
    'revision', ctx.revision,
    'updatedAt', ctx.updated_at
  );
$$;

-- Read: any active member of the selected tenant. NULL when none exists yet.
CREATE OR REPLACE FUNCTION public.albert_business_context()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
  SELECT control_plane.business_context_row_json(ctx)
  FROM control_plane.tenant_business_context AS ctx
  WHERE ctx.tenant_id = control_plane.require_current_tenant_id();
$$;

-- Write: owner/manager. p_source = 'generated' (a refresh from data: keeps the
-- owner's locks and confirmation state, bumps generated_at) or 'owner' (an
-- edit: replaces the document, records the locked sections, keeps status).
CREATE OR REPLACE FUNCTION public.albert_save_business_context(
  p_document jsonb,
  p_rendered text,
  p_source text,
  p_owner_locked jsonb DEFAULT NULL,
  p_facts jsonb DEFAULT NULL,
  p_generator_version text DEFAULT NULL,
  p_model text DEFAULT NULL,
  p_data_through timestamptz DEFAULT NULL,
  p_connectors jsonb DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  v_tenant_id text;
  v_role text;
  v_actor uuid := extensions.albert_auth_uid();
  v_row control_plane.tenant_business_context%ROWTYPE;
  v_now timestamptz := clock_timestamp();
BEGIN
  IF p_source NOT IN ('generated', 'owner') THEN
    RAISE EXCEPTION 'business context source must be generated or owner' USING ERRCODE = '22023';
  END IF;
  IF p_document IS NULL OR jsonb_typeof(p_document) <> 'object' THEN
    RAISE EXCEPTION 'business context document must be a JSON object' USING ERRCODE = '22023';
  END IF;
  IF p_rendered IS NULL OR length(btrim(p_rendered)) < 20 OR length(p_rendered) > 12000 THEN
    RAISE EXCEPTION 'business context rendering must be 20-12000 characters' USING ERRCODE = '22023';
  END IF;
  IF p_owner_locked IS NOT NULL AND jsonb_typeof(p_owner_locked) <> 'array' THEN
    RAISE EXCEPTION 'owner_locked must be a JSON array' USING ERRCODE = '22023';
  END IF;

  SELECT admin.tenant_id, admin.role INTO v_tenant_id, v_role
    FROM control_plane.current_connection_admin_membership() AS admin;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'no active organisation' USING ERRCODE = '42501';
  END IF;
  IF v_role NOT IN ('owner', 'manager') THEN
    RAISE EXCEPTION 'insufficient role for business context writes' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_row FROM control_plane.tenant_business_context WHERE tenant_id = v_tenant_id FOR UPDATE;

  IF NOT FOUND THEN
    INSERT INTO control_plane.tenant_business_context (
      tenant_id, document, rendered, facts, status, owner_locked, connectors,
      generator_version, model, data_through, generated_at, revision, updated_at, updated_by
    ) VALUES (
      v_tenant_id, p_document, p_rendered, p_facts, 'draft',
      coalesce(p_owner_locked, '[]'::jsonb), coalesce(p_connectors, '[]'::jsonb),
      p_generator_version, p_model, p_data_through,
      CASE WHEN p_source = 'generated' THEN v_now ELSE NULL END,
      1, v_now, v_actor
    ) RETURNING * INTO v_row;
  ELSIF p_source = 'generated' THEN
    UPDATE control_plane.tenant_business_context SET
      document = p_document,
      rendered = p_rendered,
      facts = coalesce(p_facts, facts),
      connectors = coalesce(p_connectors, connectors),
      generator_version = coalesce(p_generator_version, generator_version),
      model = coalesce(p_model, model),
      data_through = coalesce(p_data_through, data_through),
      generated_at = v_now,
      revision = revision + 1,
      updated_at = v_now,
      updated_by = v_actor
    WHERE tenant_id = v_tenant_id
    RETURNING * INTO v_row;
  ELSE
    UPDATE control_plane.tenant_business_context SET
      document = p_document,
      rendered = p_rendered,
      owner_locked = coalesce(p_owner_locked, owner_locked),
      revision = revision + 1,
      updated_at = v_now,
      updated_by = v_actor
    WHERE tenant_id = v_tenant_id
    RETURNING * INTO v_row;
  END IF;

  INSERT INTO control_plane.tenant_business_context_revisions (tenant_id, revision, source, document, rendered, created_by)
  VALUES (v_tenant_id, v_row.revision, p_source, v_row.document, v_row.rendered, v_actor);
  -- Keep the revision log bounded per tenant.
  DELETE FROM control_plane.tenant_business_context_revisions AS old
  WHERE old.tenant_id = v_tenant_id
    AND old.revision_id NOT IN (
      SELECT recent.revision_id FROM control_plane.tenant_business_context_revisions AS recent
      WHERE recent.tenant_id = v_tenant_id ORDER BY recent.created_at DESC LIMIT 30
    );

  RETURN control_plane.business_context_row_json(v_row);
END;
$$;

-- Confirm: the owner has read the document and accepts it as Albert's grounding.
CREATE OR REPLACE FUNCTION public.albert_confirm_business_context()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $$
DECLARE
  v_tenant_id text;
  v_role text;
  v_actor uuid := extensions.albert_auth_uid();
  v_row control_plane.tenant_business_context%ROWTYPE;
BEGIN
  SELECT admin.tenant_id, admin.role INTO v_tenant_id, v_role
    FROM control_plane.current_connection_admin_membership() AS admin;
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'no active organisation' USING ERRCODE = '42501';
  END IF;
  IF v_role NOT IN ('owner', 'manager') THEN
    RAISE EXCEPTION 'insufficient role for business context writes' USING ERRCODE = '42501';
  END IF;
  UPDATE control_plane.tenant_business_context SET
    status = 'confirmed', confirmed_at = clock_timestamp(), confirmed_by = v_actor,
    updated_at = clock_timestamp(), updated_by = v_actor
  WHERE tenant_id = v_tenant_id
  RETURNING * INTO v_row;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'no business context to confirm' USING ERRCODE = 'P0002';
  END IF;
  INSERT INTO control_plane.tenant_business_context_revisions (tenant_id, revision, source, document, rendered, created_by)
  VALUES (v_tenant_id, v_row.revision, 'confirmed', v_row.document, v_row.rendered, v_actor);
  RETURN control_plane.business_context_row_json(v_row);
END;
$$;

REVOKE ALL ON FUNCTION control_plane.business_context_row_json(control_plane.tenant_business_context) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.albert_business_context() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.albert_save_business_context(jsonb, text, text, jsonb, jsonb, text, text, timestamptz, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.albert_confirm_business_context() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.albert_business_context() TO authenticated;
GRANT EXECUTE ON FUNCTION public.albert_save_business_context(jsonb, text, text, jsonb, jsonb, text, text, timestamptz, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.albert_confirm_business_context() TO authenticated;

COMMIT;
