/**
 * GENERATED by scripts/generate-momence-openapi-coverage.mts. DO NOT EDIT.
 * Exact source lock: f290ea3b6632f2428eee22b5220ede3f5e1e5cd6a1a83c6d683a1e206a675a4a
 */
import coverageJson from "./openapi-coverage.generated.json" with { type: "json" };
import type { MomenceEntityValidationContract, MomenceOpenApiCoverage, MomenceOpenApiLeafField } from "./openapi-coverage-types.js";

export const MOMENCE_OPENAPI_COVERAGE = coverageJson as unknown as MomenceOpenApiCoverage;

/** Flat operation-context field inventory consumed by ingestion and semantic coverage checks. */
export const MOMENCE_API_FIELDS: readonly MomenceOpenApiLeafField[] = MOMENCE_OPENAPI_COVERAGE.fields;

/** Strict entity-response schemas consumed by the Momence ingestion validator. */
export const MOMENCE_ENTITY_VALIDATION_CONTRACTS: readonly MomenceEntityValidationContract[] =
  MOMENCE_OPENAPI_COVERAGE.entityValidationContracts;
