"""
Column-driven projection of Xero API records into spec-table rows.

This is a faithful port of connectors/xero/spec-sync.ts (projectStreamRows and
its helpers). Every spec column's provenance path ("accounting:Invoice.
LineItems.Quantity") is resolved against the walked record — or the exploded
element and each object enclosing it — so a projected row carries exactly the
fields the staging contract names. Row identity follows the declared grain:
vendor id, else composite key, else parent id + position, else content hash.

Keep this in lock-step with the TypeScript engine: tests/test_projection.py
asserts equality against rows the TypeScript engine produced from the same
recording (tests/expected_projection.json, regenerated by
scripts/generate-fivetran-xero-sdk-spec.ts).
"""
from __future__ import annotations

import hashlib
import json
import math
import re
from datetime import datetime, timezone
from typing import Any, Iterable

RESERVED_STAGING_COLUMNS = {
    "tenant_id", "namespaced_source_key", "connection_id", "external_account_reference",
    "source_object_type", "source_record_id", "source_version", "source_updated_at",
    "payload_hash", "payload_batch_id", "sync_run_id", "tombstone", "mapping_version",
    "first_ingested_at", "ingested_at",
}

TOMBSTONE_STATUSES = {"ARCHIVED", "DELETED"}

_MS_DATE = re.compile(r"^/Date\((-?\d+)(?:([+-])(\d{2})(\d{2}))?\)/$")
_SNAKE_1 = re.compile(r"([a-z0-9])([A-Z])")
_SNAKE_2 = re.compile(r"([A-Z]+)([A-Z][a-z])")
_SNAKE_3 = re.compile(r"[^A-Za-z0-9]+")


def snake_case(value: str) -> str:
    value = _SNAKE_1.sub(r"\1_\2", value)
    value = _SNAKE_2.sub(r"\1_\2", value)
    value = _SNAKE_3.sub("_", value)
    return value.strip("_").lower()


def source_field(column: dict) -> str:
    """The staged field name for a column (xeroSourceField in scan-plan.ts)."""
    api = column["api"]
    if api.startswith("synthetic:"):
        return column["name"]
    body = api[api.index(":") + 1:]
    body = re.sub(r"\[\]( index)?$", "", body)
    path = body.split(".")
    segments = path[1:]
    if not segments:
        return column["name"]
    base = segments[0] if len(segments) == 1 else "_".join(segments)
    return f"{path[0]}_{base}" if snake_case(base) in RESERVED_STAGING_COLUMNS else base


def js_iso(ms: int) -> str:
    """Date.prototype.toISOString for a millisecond epoch."""
    seconds, millis = divmod(ms, 1000)
    dt = datetime.fromtimestamp(seconds, tz=timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%S") + f".{millis:03d}Z"


def normalize_xero_value(value: Any) -> Any:
    """Normalize Xero's legacy /Date(ms+tz)/ values to ISO-8601."""
    if isinstance(value, str):
        match = _MS_DATE.match(value)
        if match:
            try:
                return js_iso(int(match.group(1)))
            except (ValueError, OverflowError, OSError):
                return value
    return value


def _js_number(value: float) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if math.isnan(value) or math.isinf(value):
        return "null"
    if value.is_integer() and abs(value) < 1e21:
        return str(int(value))
    text = repr(value)
    if "e" in text:
        mantissa, exponent = text.split("e")
        exponent_int = int(exponent)
        return f"{mantissa}e{'+' if exponent_int >= 0 else '-'}{abs(exponent_int)}"
    return text


def _stable_json(value: Any) -> str:
    """JSON.stringify(stableValue(v)) — sorted keys, JS number formatting."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _js_number(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ",".join(_stable_json(item) for item in value) + "]"
    if isinstance(value, dict):
        keys = sorted(value.keys(), key=lambda k: [ord(c) for c in k])
        return "{" + ",".join(json.dumps(k, ensure_ascii=False) + ":" + _stable_json(value[k]) for k in keys) + "}"
    return json.dumps(str(value), ensure_ascii=False)


def hash_payload(value: Any) -> str:
    return hashlib.sha256(_stable_json(value).encode("utf-8")).hexdigest()


def resolve_synthetic_value(column: dict, explode_path: str | None, synthetics: dict) -> Any:
    citation = column["api"]
    quoted = re.search(r"'([^']+)'", citation)
    if quoted:
        return quoted.group(1)
    for name in sorted(synthetics.keys(), key=len, reverse=True):
        value = synthetics[name]
        if value is None:
            continue
        pattern = re.compile(r"\b" + re.escape(name) + r"\b", re.IGNORECASE)
        if pattern.search(citation) or pattern.search(column["name"]):
            return value
    if explode_path and re.search(r"discriminator|branch|scope", citation):
        return explode_path.split(".")[-1]
    return None


_UNSET = object()


def _resolve_segments(record: Any, segments: Iterable[str]) -> Any:
    current = record
    for segment in segments:
        if current is None or not isinstance(current, dict):
            return _UNSET
        if segment not in current:
            return _UNSET
        current = current[segment]
    return current


def explode_rows(record: Any, segments: list[str]) -> list[dict]:
    """Expand an explode path into rows, descending through every array on the way."""
    frontier = [{"value": record, "ancestors": [], "path": []}]
    for segment in segments:
        nxt = []
        for item in frontier:
            was_array = isinstance(item["value"], list)
            containers = item["value"] if was_array else [item["value"]]
            for index, container in enumerate(containers):
                if container is None or not isinstance(container, dict):
                    continue
                if segment not in container:
                    continue
                child = container[segment]
                if child is None:
                    continue
                nxt.append({
                    "value": child,
                    "ancestors": item["ancestors"] + [container],
                    "path": item["path"] + [index] if was_array else item["path"],
                })
        frontier = nxt
    rows = []
    for item in frontier:
        elements = item["value"] if isinstance(item["value"], list) else [item["value"]]
        for ordinal, element in enumerate(elements):
            rows.append({
                "element": element,
                "ancestors": item["ancestors"],
                "ordinal": ordinal,
                "path": item["path"] + [ordinal],
            })
    return rows


def resolve_column_value(column: dict, levels: list[dict], ordinal: int,
                         explode_path: str | None, synthetics: dict) -> Any:
    api = column["api"]
    if api.startswith("synthetic:"):
        if re.search(r"(_index|_ordinal|position)$", column["name"]) or re.search(r"position|index|ordinal", api):
            return ordinal
        value = resolve_synthetic_value(column, explode_path, synthetics)
        return _UNSET if value is None else value
    body = api[api.index(":") + 1:]
    body = re.sub(r"\[\]( index)?$", "", body)

    if explode_path and body.startswith(explode_path + "."):
        value = _resolve_segments(levels[0]["value"] if levels else None, body[len(explode_path) + 1:].split("."))
        if value is not _UNSET:
            return normalize_xero_value(value)
    if explode_path and body == explode_path:
        return _UNSET if column["type"] == "jsonb" else ordinal

    parts = body.split(".")
    root, segments = parts[0], parts[1:]
    if not segments:
        return _UNSET
    named = next((level for level in levels if level["object"] == root), None)
    candidates = ([named] + levels) if named is not None else levels
    for level in candidates:
        value = _resolve_segments(level["value"], segments)
        if value is not _UNSET:
            return normalize_xero_value(value)
    for level in levels:
        value = _resolve_segments(level["value"], [root] + segments)
        if value is not _UNSET:
            return normalize_xero_value(value)
    return _UNSET


def _object_name(qualified: str) -> str:
    return qualified[qualified.index(":") + 1:] if ":" in qualified else qualified


def project_row_fields(table: dict, row: dict, walked_record: Any,
                       fan_out_parent: dict | None, synthetics: dict) -> dict:
    chain = table["source"].get("explodeChain") or []
    source_objects = table.get("sourceObjects") or []
    levels = [{
        "object": chain[-1] if chain else _object_name(source_objects[0] if source_objects else ""),
        "value": row["element"],
    }]
    ancestors = row["ancestors"]
    for index in range(len(ancestors) - 1, -1, -1):
        levels.append({"object": chain[index] if index < len(chain) else None, "value": ancestors[index]})
    if not ancestors and table["source"].get("explodePath"):
        levels.append({"object": chain[0] if chain else None, "value": walked_record})
    if fan_out_parent:
        parent_objects = fan_out_parent["table"].get("sourceObjects") or []
        levels.append({
            "object": _object_name(parent_objects[0] if parent_objects else ""),
            "value": fan_out_parent["record"],
        })
    fields: dict = {}
    for column in table["columns"]:
        value = resolve_column_value(column, levels, row["ordinal"], table["source"].get("explodePath"), synthetics)
        if value is not _UNSET:
            fields[source_field(column)] = value
    return fields


def _text(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, bool):
        out = "true" if value else "false"
    elif isinstance(value, float):
        out = _js_number(value)
    else:
        out = str(value)
    out = out.strip()
    return out if out else None


def _read_identifier(record: Any, field: str) -> str | None:
    if not field or not isinstance(record, dict):
        return None
    return _text(record.get(field))


def _leader_id_field(leader: dict) -> str:
    return leader.get("recordIdField") or (leader["primaryKey"][0] if leader["primaryKey"] else "")


def _column_by_name(table: dict, name: str) -> dict | None:
    return next((column for column in table["columns"] if column["name"] == name), None)


def _composite_key(table: dict, fields: dict) -> str | None:
    if len(table["primaryKey"]) < 2:
        return None
    parts = []
    for name in table["primaryKey"]:
        column = _column_by_name(table, name)
        if column is None:
            return None
        text = _text(fields.get(source_field(column)))
        if text is None:
            return None
        parts.append(text)
    return "|".join(parts)


def _partial_key(table: dict, fields: dict) -> str | None:
    parts = []
    for name in table["primaryKey"]:
        column = _column_by_name(table, name)
        if column is None:
            continue
        text = _text(fields.get(source_field(column)))
        if text is not None:
            parts.append(text)
    return "|".join(parts) if parts else None


def timestamp_of(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    parsed = parse_datetime(value)
    return parsed.strftime("%Y-%m-%dT%H:%M:%S") + f".{parsed.microsecond // 1000:03d}Z" if parsed else None


_ISO = re.compile(
    r"^(\d{4})-(\d{2})-(\d{2})(?:[T ](\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{1,9}))?)?)?\s*(Z|[+-]\d{2}:?\d{2})?$"
)


def parse_datetime(value: Any) -> datetime | None:
    """Parse ISO-8601 (any fractional precision) or /Date(ms)/ into an aware UTC datetime."""
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if not isinstance(value, str):
        return None
    match = _MS_DATE.match(value)
    if match:
        try:
            return datetime.fromtimestamp(int(match.group(1)) / 1000, tz=timezone.utc)
        except (ValueError, OverflowError, OSError):
            return None
    match = _ISO.match(value.strip())
    if not match:
        return None
    year, month, day, hour, minute, second, fraction, zone = match.groups()
    micro = int((fraction or "0")[:6].ljust(6, "0"))
    try:
        dt = datetime(int(year), int(month), int(day), int(hour or 0), int(minute or 0), int(second or 0), micro,
                      tzinfo=timezone.utc)
    except ValueError:
        return None
    if zone and zone != "Z":
        sign = 1 if zone[0] == "+" else -1
        digits = zone[1:].replace(":", "")
        offset_minutes = sign * (int(digits[:2]) * 60 + int(digits[2:]))
        from datetime import timedelta
        dt = dt - timedelta(minutes=offset_minutes)
    return dt


def project_stream_rows(table: dict, leader_table: dict, records: list, record_id_field: str,
                        fan_out_parent: dict | None = None, synthetics: dict | None = None) -> list[dict]:
    """
    Project one page of walked records into one table's rows. Returns dicts of
    {sourceRecordId, fields, tombstone, updatedAt, payload}.
    """
    synthetics = synthetics or {}
    explode = table["source"].get("explodePath")
    modified_field = table["source"].get("modifiedField") or ""
    rows: list[dict] = []
    for record_index, record in enumerate(records):
        if record is None or not isinstance(record, dict):
            continue
        if fan_out_parent:
            parent_id = _read_identifier(fan_out_parent["record"], _leader_id_field(fan_out_parent["table"]))
        else:
            parent_id = _read_identifier(record, _leader_id_field(leader_table))
        exploded = (explode_rows(record, explode.split(".")[1:]) if explode
                    else [{"element": record, "ancestors": [], "ordinal": record_index, "path": [record_index]}])
        for row in exploded:
            element = row["element"]
            if element is None:
                continue
            fields = project_row_fields(table, row, record, fan_out_parent, synthetics)
            composite = _composite_key(table, fields)
            own_id = composite or _read_identifier(fields, record_id_field) or _read_identifier(element, record_id_field)
            position_key = ".".join(str(part) for part in row["path"])
            declared_key = _partial_key(table, fields)
            if own_id:
                source_record_id = own_id
            elif parent_id:
                source_record_id = f"{parent_id}:{declared_key or position_key}"
            elif declared_key:
                source_record_id = f"{table['id']}:{declared_key}"
            else:
                source_record_id = f"{table['id']}:{hash_payload(element)[:32]}"
            updated_at = timestamp_of(fields.get(modified_field)) if modified_field else None
            if not updated_at and modified_field and isinstance(record, dict) and modified_field in record:
                updated_at = timestamp_of(normalize_xero_value(record[modified_field]))
            status = str(fields.get("Status", fields.get("ContactStatus", "")) or "")
            rows.append({
                "sourceRecordId": source_record_id,
                "fields": fields,
                "tombstone": status in TOMBSTONE_STATUSES,
                "updatedAt": updated_at,
                "payload": element if explode else record,
            })
    return rows


def unwrap_envelope(body: Any, table: dict) -> list:
    """Unwrap a Xero response envelope into its record array (unwrapEnvelope in spec-sync.ts)."""
    if isinstance(body, list):
        return body
    if body is None or not isinstance(body, dict):
        return []
    array_key = table["source"].get("arrayKey")
    if array_key:
        current: Any = body
        for segment in array_key.split("."):
            if current is None or not isinstance(current, dict):
                current = None
                break
            host = current
            lowered = segment[:1].lower() + segment[1:]
            current = host.get(segment) if host.get(segment) is not None else host.get(lowered)
        if isinstance(current, list):
            return current
        if isinstance(current, dict):
            return [current]
    for value in body.values():
        if isinstance(value, list):
            return value
    return []
