"""
Projection of Lightspeed R-Series walk pages into spec-table rows.

A faithful port of the row projection in connectors/lightspeed-r/fetch-core.ts
and spec-sync.ts (`parseEnvelope`, `resolvePath`, `readSourceUpdatedAt`,
`projectStreamRows`): every member of a scan group projects its rows out of the
same walked page — the leader 1:1, nested members one row per element of the
array at their `projectFrom` path — and a nested row carries the parent-context
leaves the spec declares (Sale.completed on a sale line) under their leaf name.

Row identity follows the TypeScript engine exactly: the member's own record-id
field, else parent id + position, else table id + position.

Keep this in lock-step with the TypeScript engine: tests/test_projection.py
asserts equality against rows the TypeScript engine produced from the same
walk pages (tests/expected_projection.json, regenerated by
scripts/generate-fivetran-lightspeed-sdk-spec.ts).
"""
from __future__ import annotations

import re
from datetime import datetime, timedelta, timezone
from typing import Any

_ISO = re.compile(
    r"^(\d{4})-(\d{2})-(\d{2})(?:[T ](\d{2}):(\d{2})(?::(\d{2})(?:\.(\d{1,9}))?)?)?\s*(Z|[+-]\d{2}:?\d{2})?$"
)


def parse_datetime(value: Any) -> datetime | None:
    """Parse an ISO-8601 timestamp (any fractional precision, any zone) into aware UTC."""
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if not isinstance(value, str):
        return None
    match = _ISO.match(value.strip())
    if not match:
        return None
    year, month, day, hour, minute, second, fraction, zone = match.groups()
    micro = int((fraction or "0")[:6].ljust(6, "0"))
    try:
        parsed = datetime(int(year), int(month), int(day), int(hour or 0), int(minute or 0), int(second or 0),
                          micro, tzinfo=timezone.utc)
    except ValueError:
        return None
    if zone and zone != "Z":
        sign = 1 if zone[0] == "+" else -1
        digits = zone[1:].replace(":", "")
        parsed = parsed - timedelta(minutes=sign * (int(digits[:2]) * 60 + int(digits[2:])))
    return parsed


def js_iso(moment: datetime) -> str:
    """Date.prototype.toISOString: millisecond precision, trailing Z."""
    moment = moment.astimezone(timezone.utc)
    return moment.strftime("%Y-%m-%dT%H:%M:%S") + f".{moment.microsecond // 1000:03d}Z"


def parse_envelope(body: Any, resource: str) -> dict:
    """
    Unwrap an R-Series envelope: records live under a key named for the
    resource, a single result is an object rather than an array, and
    `@attributes.next` carries the continuation URL on non-terminal pages.
    """
    if body is None or not isinstance(body, dict):
        raise ValueError("Vendor response was not a JSON object.")
    attributes = body.get("@attributes") or {}
    if not isinstance(attributes, dict):
        attributes = {}
    raw = body.get(resource)
    if raw is None:
        records: list = []
    elif isinstance(raw, list):
        records = [item for item in raw if isinstance(item, dict)]
    elif isinstance(raw, dict):
        records = [raw]
    else:
        records = []
    next_raw = attributes.get("next")
    next_url = next_raw if isinstance(next_raw, str) and next_raw else None
    count_raw = attributes.get("count")
    try:
        reported = int(count_raw) if count_raw is not None else None
    except (TypeError, ValueError):
        reported = None
    return {"records": records, "nextUrl": next_url, "reportedCount": reported}


def after_token(next_url: str | None) -> str | None:
    """Extract the opaque `after` continuation from the vendor's next URL."""
    if not next_url:
        return None
    from urllib.parse import parse_qs, urlparse
    try:
        query = parse_qs(urlparse(next_url).query)
        values = query.get("after")
        if values:
            return values[0]
    except ValueError:
        pass
    match = re.search(r"[?&]after=([^&]+)", next_url)
    if match:
        from urllib.parse import unquote
        return unquote(match.group(1))
    return None


def resolve_path(record: Any, path: str) -> list:
    """Resolve a dot path inside a record, tolerating R-Series' singular wrappers."""
    current: Any = record
    for segment in [part for part in path.split(".") if part]:
        if current is None or not isinstance(current, dict):
            return []
        if segment not in current:
            return []
        current = current[segment]
    if current is None:
        return []
    return current if isinstance(current, list) else [current]


def read_source_updated_at(record: dict) -> str | None:
    """R-Series exposes last-modified as `timeStamp` on most resources."""
    for key in ("timeStamp", "updateTime", "createTime"):
        value = record.get(key)
        if isinstance(value, str) and value:
            parsed = parse_datetime(value)
            if parsed:
                return js_iso(parsed)
    return None


def read_id(record: Any, field: str) -> str | None:
    if not isinstance(record, dict) or not field:
        return None
    value = record.get(field)
    if value is None:
        return None
    if isinstance(value, bool):
        text = "true" if value else "false"
    elif isinstance(value, float) and value.is_integer():
        text = str(int(value))
    else:
        text = str(value)
    text = text.strip()
    return text if text and text != "0" else None


# Nested-array keys the live API returns under a different name than the
# documented relation: Item.json answers `load_relations=["ItemPrices"]` with
# a `Prices` object (observed live 2026-08-17; connectors/lightspeed-r
# field-coverage.ts records `Prices` in the quarantine census for the same
# reason). The documented path is tried first, then the alias.
PROJECT_FROM_ALIASES = {
    "ItemPrices.ItemPrice": "Prices.ItemPrice",
}


def project_member_rows(group: dict, member: dict, records: list) -> list[dict]:
    """
    Project one walked page into one member table's rows. Returns dicts of
    {sourceRecordId, sourceObjectType, updatedAt, fields} where `fields` is the
    row payload keyed by vendor field name (parent-context leaves included).
    """
    out: list[dict] = []
    id_field = member.get("recordIdField") or ""
    project_from = member.get("projectFrom")
    parent_leaves = member.get("parentLeaves") or []
    for record in records:
        if not isinstance(record, dict):
            continue
        rows = resolve_path(record, project_from) if project_from else [record]
        if project_from and not rows and project_from in PROJECT_FROM_ALIASES:
            rows = resolve_path(record, PROJECT_FROM_ALIASES[project_from])
        for row in rows:
            if row is None or not isinstance(row, dict):
                continue
            payload = dict(row)
            # Parent context rides the child under its leaf name, but only when
            # the child does not already carry that key (a child null stays null).
            for leaf in parent_leaves:
                if leaf in payload or leaf not in record:
                    continue
                payload[leaf] = record[leaf]
            own_id = read_id(payload, id_field) if id_field else None
            parent_id = read_id(record, group["idField"])
            if own_id:
                source_record_id = own_id
            elif parent_id:
                source_record_id = f"{parent_id}:{len(out)}"
            else:
                source_record_id = f"{member['table']}:{len(out)}"
            updated_at = read_source_updated_at(payload) or read_source_updated_at(record)
            out.append({
                "sourceRecordId": source_record_id,
                "sourceObjectType": member["resource"],
                "updatedAt": updated_at,
                "fields": payload,
            })
    return out


def project_fan_out_rows(fan_out: dict, parent_id: str, children: list, offset: int = 0) -> list[dict]:
    """One row per child record of a parent-scoped endpoint (syncFanOutPage)."""
    out: list[dict] = []
    id_field = fan_out.get("recordIdField") or ""
    for child in children:
        if not isinstance(child, dict):
            continue
        own_id = read_id(child, id_field) if id_field else None
        out.append({
            "sourceRecordId": own_id or f"{parent_id}:{offset + len(out)}",
            "sourceObjectType": fan_out["resource"],
            "updatedAt": read_source_updated_at(child),
            "fields": child,
        })
    return out
