import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { Client } from "pg";
import { ulid } from "ulid";
import { deputyManifest } from "../connectors/deputy/manifest.js";
import { lightspeedRManifest } from "../connectors/lightspeed-r/manifest.js";
import { googleAdsManifest } from "../connectors/google-ads/manifest.js";
import { metaAdsManifest } from "../connectors/meta-ads/manifest.js";
import { momenceManifest } from "../connectors/momence/manifest.js";
import { shopifyManifest } from "../connectors/shopify/manifest.js";
import { squareManifest } from "../connectors/square/manifest.js";
import { stripeManifest } from "../connectors/stripe/manifest.js";
import { xeroManifest } from "../connectors/xero/manifest.js";
import { buildGovernedSourceCatalogueFields } from "../packages/connector-sdk/src/index.js";
import {
  combineCatalogueDocuments,
  assertCapabilityContract,
  createRegistryCatalogueDocuments,
  createSourceFieldCatalogueDocuments,
  createSemanticPublicationPlan,
  generateCanonicalSchemaDoc,
  generateRegistryDocumentation,
  parseRegistryDocument,
} from "../packages/semantic-registry/src/index.js";
import {
  OpenAIEmbeddingProvider,
  serializePgVector,
} from "../services/semantic-query/src/embeddings.js";

const REGISTRY_PATH = resolve("packages/semantic-registry/registry/registry.yaml");
const GENERATED_DOCUMENTATION_PATH = resolve("docs/generated/semantic-registry.md");
const GENERATED_SCHEMA_DOC_PATH = resolve("packages/agent/src/generated-canonical-schema.ts");
const ALLOWED_ACTIONS = new Set(["check", "write", "publish"]);
const FORBIDDEN_PUBLISH_ROLES = new Set(["anon", "authenticated", "ingest_rw", "semantic_ro"]);

type Action = "check" | "write" | "publish";

function actionFromArguments(arguments_: readonly string[]): Action {
  const action = arguments_[0] ?? "check";
  if (!ALLOWED_ACTIONS.has(action)) {
    throw new Error("Registry action must be check, write, or publish.");
  }
  return action as Action;
}

function quoteIdentifier(value: string): string {
  if (!/^[a-z_][a-z0-9_]{0,62}$/.test(value)) {
    throw new Error(`Invalid PostgreSQL role identifier: ${value}`);
  }
  return `"${value}"`;
}

async function loadArtifacts() {
  const source = await readFile(REGISTRY_PATH, "utf8");
  const document = parseRegistryDocument(source);
  const connectorManifests = [deputyManifest,googleAdsManifest,lightspeedRManifest,metaAdsManifest,momenceManifest,shopifyManifest,squareManifest,stripeManifest,xeroManifest] as const;
  assertCapabilityContract(document,connectorManifests);
  const packVersions = {
    [deputyManifest.id]: deputyManifest.packVersion,
    [lightspeedRManifest.id]: lightspeedRManifest.packVersion,
    [xeroManifest.id]: xeroManifest.packVersion,
    [squareManifest.id]: squareManifest.packVersion,
    [shopifyManifest.id]: shopifyManifest.packVersion,
    [stripeManifest.id]: stripeManifest.packVersion,
    [momenceManifest.id]: momenceManifest.packVersion,
    [metaAdsManifest.id]: metaAdsManifest.packVersion,
    [googleAdsManifest.id]: googleAdsManifest.packVersion,
  };
  return Object.freeze({
    documents: combineCatalogueDocuments(
      createRegistryCatalogueDocuments(document),
      createSourceFieldCatalogueDocuments(buildGovernedSourceCatalogueFields(connectorManifests)),
    ),
    documentation: generateRegistryDocumentation(document),
    schemaDocModule: renderSchemaDocModule(generateCanonicalSchemaDoc(document), document.registryVersion),
    plan: createSemanticPublicationPlan(document, packVersions),
  });
}

function renderSchemaDocModule(schemaDoc: string, registryVersion: string): string {
  return `// Generated by \`npm run registry:write\` from registry ${registryVersion}. Do not hand-edit.\n\n/** The canonical model as the agent sees it before writing SQL. */\nexport const CANONICAL_SCHEMA_DOC = ${JSON.stringify(schemaDoc)};\n`;
}

async function assertGeneratedDocumentation(expected: string, expectedSchemaModule: string): Promise<void> {
  const current = await readFile(GENERATED_DOCUMENTATION_PATH, "utf8").catch(() => "");
  const currentSchemaModule = await readFile(GENERATED_SCHEMA_DOC_PATH, "utf8").catch(() => "");
  if (current !== expected || currentSchemaModule !== expectedSchemaModule) {
    throw new Error(
      "Generated semantic registry documentation is stale. Run `npm run registry:write`.",
    );
  }
}

async function publish(artifacts: Awaited<ReturnType<typeof loadArtifacts>>): Promise<void> {
  const { documents, plan } = artifacts;
  const databaseUrl = process.env.CONTROL_PLANE_DATABASE_URL?.trim();
  if (!databaseUrl) throw new Error("CONTROL_PLANE_DATABASE_URL is required to publish.");
  const publicationRole = process.env.ALBERT_SEMANTIC_PUBLISH_ROLE?.trim() || "albert_control_migration_owner";
  if (publicationRole !== "albert_control_migration_owner") {
    throw new Error("Semantic publication must use albert_control_migration_owner.");
  }
  const embeddingProvider = new OpenAIEmbeddingProvider({
    apiKey: process.env.OPENAI_API_KEY,
    baseURL: process.env.OPENAI_BASE_URL,
    timeoutMs: 30_000,
  });
  const embeddings = await embeddingProvider.embedDocuments(documents.map(({ content }) => content));
  const indexedDocuments = documents.map((document, index) => ({
    document_id: document.id,
    kind: document.kind,
    registry_version: plan.registryVersion,
    title: document.title,
    content: document.content,
    content_hash: document.contentHash,
    embedding_model: embeddingProvider.model,
    embedding_dimensions: embeddingProvider.dimensions,
    embedding: serializePgVector(embeddings[index] ?? []),
    metadata: document.metadata,
  }));
  const client = new Client({
    connectionString: databaseUrl,
    application_name: `albert-semantic-publisher/${plan.registryVersion}`,
  });
  await client.connect();
  try {
    await client.query("BEGIN");
    await client.query(`SET LOCAL ROLE ${quoteIdentifier(publicationRole)}`);
    const identity = await client.query<{ current_user: string; session_user: string }>(
      "SELECT current_user, session_user",
    );
    const currentRole = identity.rows[0]?.current_user;
    if (!currentRole || FORBIDDEN_PUBLISH_ROLES.has(currentRole)) {
      throw new Error(`Refusing to publish as runtime role ${currentRole ?? "unknown"}.`);
    }
    if (
      process.env.ALBERT_REQUIRE_DEPLOYER_LOGIN === "true" &&
      identity.rows[0]?.session_user !== "albert_control_deployer"
    ) {
      throw new Error("Semantic publication must use the albert_control_deployer login.");
    }
    await client.query(
      "SELECT pg_advisory_xact_lock(hashtextextended('albert:semantic-publication', 0))",
    );

    const sameVersion = await client.query<{
      publication_id: string;
      registry_hash: string;
      status: string;
      snapshot_matches: boolean;
    }>(
      `SELECT publication_id,registry_hash,status,
              pack_versions=$2::jsonb AND manifest=$3::jsonb AS snapshot_matches
       FROM control_plane.semantic_publications
       WHERE registry_version=$1
       FOR UPDATE`,
      [plan.registryVersion, JSON.stringify(plan.packVersions), JSON.stringify(plan.manifest)],
    );
    const existing = sameVersion.rows[0];
    if (
      existing &&
      (existing.registry_hash !== plan.registryHash || !existing.snapshot_matches)
    ) {
      throw new Error(
        `Registry ${plan.registryVersion} already identifies a different immutable deployment snapshot.`,
      );
    }
    const publicationId = existing?.publication_id ?? ulid();
    if (existing?.status !== "published") {
      await client.query(
        `UPDATE control_plane.semantic_publications
         SET status='superseded',superseded_at=now()
         WHERE status='published'`,
      );
      await client.query(
        `INSERT INTO control_plane.semantic_publications (
         publication_id,registry_version,registry_hash,schema_version,
         contract_count,topic_count,pack_versions,manifest,status,published_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,'published',now())
       ON CONFLICT (registry_version) DO UPDATE SET
         status='published',published_at=now(),superseded_at=NULL
       WHERE control_plane.semantic_publications.registry_hash=EXCLUDED.registry_hash`,
        [
          publicationId,
          plan.registryVersion,
          plan.registryHash,
          plan.schemaVersion,
          plan.contractCount,
          plan.topicCount,
          JSON.stringify(plan.packVersions),
          JSON.stringify(plan.manifest),
        ],
      );
    }
    await client.query(
      `INSERT INTO control_plane.catalogue_documents (
         publication_id,document_id,kind,registry_version,title,content,content_hash,
         embedding_model,embedding_dimensions,embedding,metadata
       )
       SELECT $1,d.document_id,d.kind,d.registry_version,d.title,d.content,d.content_hash,
              d.embedding_model,d.embedding_dimensions,d.embedding::extensions.vector(1536),d.metadata
       FROM jsonb_to_recordset($2::jsonb) AS d(
         document_id text,kind text,registry_version text,title text,content text,
         content_hash text,embedding_model text,embedding_dimensions integer,
         embedding text,metadata jsonb
       )
       ON CONFLICT (publication_id,document_id) DO NOTHING`,
      [publicationId,JSON.stringify(indexedDocuments)],
    );
    const stored = await client.query<{
      document_id:string;
      content_hash:string;
      embedding_model:string;
      embedding_dimensions:number;
    }>(
      `SELECT document_id,content_hash,embedding_model,embedding_dimensions
       FROM control_plane.catalogue_documents
       WHERE publication_id=$1
       ORDER BY document_id`,
      [publicationId],
    );
    const expectedById = new Map(documents.map((document) => [document.id,document.contentHash]));
    if (stored.rows.length !== documents.length || stored.rows.some((row) =>
      expectedById.get(row.document_id) !== row.content_hash ||
      row.embedding_model !== embeddingProvider.model ||
      Number(row.embedding_dimensions) !== embeddingProvider.dimensions
    )) {
      throw new Error(`Catalogue index for ${plan.registryVersion} is incomplete or differs from its immutable registry snapshot.`);
    }
    await client.query("COMMIT");
    process.stdout.write(
      `${existing?.status === "published" ? "verified" : "published"} semantic-registry/${plan.registryVersion} ${plan.registryHash} (${documents.length} indexed documents)\n`,
    );
  } catch (error) {
    await client.query("ROLLBACK").catch(() => undefined);
    throw error;
  } finally {
    await client.end();
  }
}

async function main(): Promise<void> {
  const action = actionFromArguments(process.argv.slice(2));
  const artifacts = await loadArtifacts();
  if (action === "write") {
    await mkdir(dirname(GENERATED_DOCUMENTATION_PATH), { recursive: true });
    await writeFile(GENERATED_DOCUMENTATION_PATH, artifacts.documentation, "utf8");
    await writeFile(GENERATED_SCHEMA_DOC_PATH, artifacts.schemaDocModule, "utf8");
    process.stdout.write(`generated ${GENERATED_DOCUMENTATION_PATH}\n`);
    process.stdout.write(`generated ${GENERATED_SCHEMA_DOC_PATH}\n`);
    return;
  }
  await assertGeneratedDocumentation(artifacts.documentation, artifacts.schemaDocModule);
  if (action === "publish") await publish(artifacts);
}

await main();
