/**
 * Build the connector playbooks injected into the Albert agent prompt.
 *
 * A playbook is domain orientation for one source: how a shop owner's words map
 * onto that system's grains, which reading is honest, and which correct-looking
 * query is commercially wrong. It is deliberately NOT a second copy of the
 * schema — `write-staging-schema-doc.mts` emits the table index and column
 * dictionaries from the live DDL.
 *
 * Source of truth: `connectors/<id>/playbooks/core.md` (always injected) plus
 * one `<dimension>.md` per dimension guide (injected by intent domain, and on
 * demand via the open_dimension_guide tool).
 *
 * Run: npm run generate:connector-playbooks
 *      npm run generate:connector-playbooks -- --check   (CI freshness gate)
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve, join, basename } from "node:path";

/** Connectors that ship playbooks today. Add an id once its pages exist. */
const PLAYBOOK_CONNECTORS = ["lightspeed-r"] as const;

const cores: Record<string, string> = {};
const guides: Record<string, Record<string, string>> = {};

for (const connectorId of PLAYBOOK_CONNECTORS) {
  const dir = resolve(`connectors/${connectorId}/playbooks`);
  if (!existsSync(join(dir, "core.md"))) {
    throw new Error(`connector_playbook_core_missing:${connectorId}`);
  }
  const core = readFileSync(join(dir, "core.md"), "utf8").trim();
  if (!core) throw new Error(`connector_playbook_core_empty:${connectorId}`);
  cores[connectorId] = core;

  const dimensionGuides: Record<string, string> = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".md")).sort()) {
    const name = basename(file, ".md");
    if (name === "core") continue;
    const body = readFileSync(join(dir, file), "utf8").trim();
    if (!body) throw new Error(`connector_playbook_guide_empty:${connectorId}:${name}`);
    dimensionGuides[name] = body;
  }
  if (Object.keys(dimensionGuides).length === 0) {
    throw new Error(`connector_playbook_guides_missing:${connectorId}`);
  }
  guides[connectorId] = dimensionGuides;
}

const body = `// Generated by scripts/write-connector-playbook-doc.mts from connectors/*/playbooks/*.md. Do not hand-edit.\n`
  + `// Regenerate: npm run generate:connector-playbooks. CI freshness: npm run generate:connector-playbooks -- --check.\n\n`
  + `/**\n`
  + ` * Always-injected orientation per connector: gates, owner-phrase map, grains,\n`
  + ` * name resolution, population map, cross-cutting traps, hard limits.\n`
  + ` */\n`
  + `export const CONNECTOR_PLAYBOOK_CORES: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(cores, null, 2)});\n\n`
  + `/**\n`
  + ` * Per-dimension deep guides (money semantics, traps, worked SQL shapes),\n`
  + ` * injected by intent domain and on demand via open_dimension_guide.\n`
  + ` */\n`
  + `export const CONNECTOR_DIMENSION_GUIDES: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.freeze(${JSON.stringify(guides, null, 2)});\n\n`
  + `/** The always-injected core playbook for a connector, or "" when it ships none. */\n`
  + `export function connectorPlaybookCore(connectorId: string): string {\n`
  + `  return CONNECTOR_PLAYBOOK_CORES[connectorId] ?? "";\n`
  + `}\n\n`
  + `/** One dimension guide, or "" when the connector or guide does not exist. */\n`
  + `export function connectorDimensionGuide(connectorId: string, dimension: string): string {\n`
  + `  return CONNECTOR_DIMENSION_GUIDES[connectorId]?.[dimension] ?? "";\n`
  + `}\n\n`
  + `/** Guide names available for a connector. */\n`
  + `export function connectorDimensionGuideNames(connectorId: string): readonly string[] {\n`
  + `  return Object.freeze(Object.keys(CONNECTOR_DIMENSION_GUIDES[connectorId] ?? {}));\n`
  + `}\n`;

const outPath = resolve("packages/agent/src/generated-connector-playbooks.ts");
const check = process.argv.includes("--check");
if (check) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current !== body) {
    console.error("generated-connector-playbooks.ts is stale. Run: npm run generate:connector-playbooks");
    process.exit(1);
  }
  console.log("generated-connector-playbooks.ts is fresh.");
} else {
  writeFileSync(outPath, body);
  const guideCount = Object.values(guides).reduce((sum, g) => sum + Object.keys(g).length, 0);
  console.log(`wrote ${outPath} (${Object.keys(cores).length} core(s), ${guideCount} dimension guide(s))`);
}
