\set ON_ERROR_STOP on

BEGIN;

CREATE OR REPLACE FUNCTION pg_temp.assert_true(value boolean,message text)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  IF value IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'protected-dogfood M6 assertion failed: %',message;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION pg_temp.append_event(
  p_tenant text,p_conversation text,p_turn text,p_sequence integer,p_event jsonb
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE observed timestamptz:=clock_timestamp();event_id text:=control_plane.generate_ulid();
BEGIN
  INSERT INTO control_plane.conversation_turn_events(
    tenant_id,turn_event_id,conversation_id,turn_id,sequence_number,event,occurred_at
  ) VALUES (
    p_tenant,event_id,p_conversation,p_turn,p_sequence,
    p_event||jsonb_build_object(
      'id',event_id,'sequence',p_sequence,'occurredAt',observed
    ),observed
  );
END;
$$;

CREATE OR REPLACE FUNCTION pg_temp.provenance(
  p_bundle text,p_sources jsonb,p_definitions jsonb,
  p_label text,p_start timestamptz,p_end timestamptz
) RETURNS jsonb LANGUAGE sql IMMUTABLE AS $$
  SELECT jsonb_build_object(
    'sources',p_sources,
    'timeRange',jsonb_build_object(
      'label',p_label,'start',p_start,'end',p_end,'timezone','Australia/Melbourne'
    ),
    'definitions',p_definitions,
    'semanticBundleHash',p_bundle,
    'identityGraph',jsonb_build_object(
      'version',7,'hash','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb'
    )
  )
$$;

-- Fixed vector generated by services/semantic-query/src/bundle.ts
-- contentDigest.  This prevents the SQL implementation and the test fixture
-- from drifting together while still accepting different encodings.
SELECT pg_temp.assert_true(
  control_plane.dogfood_stable_json_sha256(
    '{
      "columns":["worker","rostered_hours"],
      "rows":[
        {"rostered_hours":"8.0000","worker":"worker-01"},
        {"rostered_hours":null,"worker":"worker-02"}
      ]
    }'::jsonb
  )='df226e26fdc23c041ab8eeda069bba3c6e6c959f6c0f3828f6c47c5794542453',
  'stable JSON digest must match the semantic service contentDigest vector'
);

INSERT INTO auth.users(
  id,aud,role,email,encrypted_password,email_confirmed_at,
  raw_app_meta_data,raw_user_meta_data,created_at,updated_at
) VALUES (
  '63000000-0000-4000-8000-000000000063','authenticated','authenticated',
  'dogfood-m6-lineage@albert.invalid','',now(),'{}','{}',now(),now()
);

INSERT INTO control_plane.tenants(
  tenant_id,slug,display_name,status,created_by,created_at,updated_at
) VALUES (
  '01K30000000000000000000630','dogfood-m6-lineage',
  'Dogfood M6 lineage','active','63000000-0000-4000-8000-000000000063',
  clock_timestamp(),clock_timestamp()
);
INSERT INTO control_plane.memberships(
  tenant_id,membership_id,user_id,role,status,created_by
) VALUES (
  '01K30000000000000000000630','01K30000000000000000000631',
  '63000000-0000-4000-8000-000000000063','owner','active',
  '63000000-0000-4000-8000-000000000063'
);

SELECT clock_timestamp()-interval '1 minute' AS m6_barrier \gset
WITH anchor AS (
  SELECT clock_timestamp() AS now_at,
         clock_timestamp() AT TIME ZONE 'Australia/Melbourne' AS local_now
),periods AS (
  SELECT now_at,
         date_trunc('day',local_now) AT TIME ZONE 'Australia/Melbourne' AS roster_start,
         (date_trunc('day',local_now)+interval '1 day')
           AT TIME ZONE 'Australia/Melbourne' AS roster_end,
         date_trunc('month',local_now) AT TIME ZONE 'Australia/Melbourne' AS category_start
    FROM anchor
)
SELECT roster_start,roster_end,category_start,roster_end AS category_end,
       now_at-interval '6 months' AS performance_from,now_at AS performance_to
  FROM periods \gset

-- The founding question must first produce and content-address the exact
-- three-choice clarification.
INSERT INTO control_plane.conversations(
  tenant_id,conversation_id,status,created_by
) VALUES (
  '01K30000000000000000000630','01K30000000000000000000632','active',
  '63000000-0000-4000-8000-000000000063'
);
INSERT INTO control_plane.conversation_turns(
  tenant_id,turn_id,conversation_id,turn_number,user_message,
  runtime_profile,status,created_by
) VALUES (
  '01K30000000000000000000630','01K30000000000000000000633',
  '01K30000000000000000000632',1,
  'Which of my employees working today performed best over the last six months?',
  '{"model":"gpt-5.6-sol","reasoningEffort":"high","fastMode":true,"runtime":"openai-agents-sdk"}',
  'running','63000000-0000-4000-8000-000000000063'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000633',1,
  '{"type":"progress","status":"running","label":"Understanding the question"}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000633',2,
  '{"type":"narrative","status":"running","text":"I’m matching the question to Albert’s governed business definitions."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000633',3,
  '{"type":"narrative","status":"complete","text":"I checked that the connected sources can support this analysis before querying."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000633',4,
  '{
    "type":"clarification","status":"complete",
    "question":"What should ‘performed best’ mean for this answer?",
    "options":[
      {"id":"employee.net_sales","label":"Net sales"},
      {"id":"employee.gross_margin","label":"Gross profit"},
      {"id":"employee.gross_profit_per_labour_hour","label":"Gross profit per worked hour"}
    ]
  }'
);

SELECT set_config('albert.tenant_id','01K30000000000000000000630',true);
SELECT * FROM control_plane.finalize_answer_artifact(
  '01K30000000000000000000630',
  '63000000-0000-4000-8000-000000000063'::uuid,
  '01K30000000000000000000632','01K30000000000000000000633',
  'resp_dogfood_m6_clarification','{"requests":1,"inputTokens":20,"outputTokens":5}',
  'clarification','sha256:'||repeat('1',64),
  '{
    "rateCardId":"openai-2026.08.04","model":"gpt-5.6-sol","fastMode":true,
    "requests":1,"inputTokens":20,"cachedInputTokens":0,"cacheWriteInputTokens":0,
    "outputTokens":5,"estimatedCostUsdMicros":100,"pricingCompleteness":"request_level"
  }',
  '[]'
) \gset flagship_clarification_

-- The selected chip is consumed once by the exact answer turn.
INSERT INTO control_plane.conversation_turns(
  tenant_id,turn_id,conversation_id,turn_number,user_message,
  runtime_profile,status,created_by
) VALUES (
  '01K30000000000000000000630','01K30000000000000000000634',
  '01K30000000000000000000632',2,'Net sales',
  '{"model":"gpt-5.6-sol","reasoningEffort":"high","fastMode":true,"runtime":"openai-agents-sdk"}',
  'running','63000000-0000-4000-8000-000000000063'
);
UPDATE control_plane.clarification_prompts
   SET consumed_turn_id='01K30000000000000000000634',
       consumed_option_id='employee.net_sales',consumed_at=clock_timestamp()
 WHERE tenant_id='01K30000000000000000000630'
   AND offered_turn_id='01K30000000000000000000633';

SELECT control_plane.dogfood_stable_json_sha256(jsonb_build_object(
  'columns','["worker","rostered_hours"]'::jsonb,
  'rows','[{"worker":"Sam","rostered_hours":"8.0000"}]'::jsonb
)) AS roster_result_digest \gset
SELECT control_plane.dogfood_stable_json_sha256(jsonb_build_object(
  'columns','["worker","net_sales_ex_gst","worked_hours","sales_per_labour_hour"]'::jsonb,
  'rows','[{"worker":"Sam","net_sales_ex_gst":"15000.0000","worked_hours":"800.0000","sales_per_labour_hour":"18.7500"}]'::jsonb
)) AS performance_result_digest \gset

SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',1,
  '{"type":"progress","status":"running","label":"Understanding the question"}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',2,
  '{"type":"narrative","status":"running","text":"I’m matching the question to Albert’s governed business definitions."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',3,
  '{"type":"narrative","status":"complete","text":"I checked that the connected sources can support this analysis before querying."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',4,
  '{"type":"progress","status":"running","label":"Running the governed analysis"}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',5,
  jsonb_build_object(
    'type','query','status','complete','topic','workforce_labour',
    'metrics','["rostered_hours"]'::jsonb,'dimensions','["worker"]'::jsonb,
    'timeRange',jsonb_build_object(
      'label','Today','start',:'roster_start'::timestamptz,
      'end',:'roster_end'::timestamptz,
      'timezone','Australia/Melbourne'
    ),'lens','Rostered hours'
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',6,
  jsonb_build_object(
    'type','table','status','complete','caption','Workforce labour · Today',
    'columns','[
      {"key":"worker","label":"Worker","type":"string"},
      {"key":"rostered_hours","label":"Rostered hours","type":"number"}
    ]'::jsonb,
    'rows','[{"worker":"Sam","rostered_hours":"8.0000"}]'::jsonb,
    'resultId','semantic:'||repeat('a',64),
    'provenance',pg_temp.provenance(
      repeat('a',64),
      '[{"connector":"deputy","label":"Deputy","dataThrough":"2026-08-04T13:55:00Z"}]',
      '[{"metric":"workforce.rostered_hours","label":"Rostered hours","definition":"Planned governed shift hours."}]',
      'Today',:'roster_start'::timestamptz,:'roster_end'::timestamptz
    )
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',7,
  '{"type":"validation","status":"complete","name":"shift_timesheet_coverage","outcome":"passed","detail":"Shift coverage passed."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',8,
  '{"type":"narrative","status":"complete","text":"Worker Sam is rostered today."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',9,
  '{"type":"progress","status":"running","label":"Running the governed analysis"}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',10,
  jsonb_build_object(
    'type','query','status','complete','topic','workforce_sales',
    'metrics','["sales_per_labour_hour"]'::jsonb,'dimensions','["worker"]'::jsonb,
    'timeRange',jsonb_build_object(
      'label','Last six months','start',:'performance_from'::timestamptz,
      'end',:'performance_to'::timestamptz,'timezone','Australia/Melbourne'
    ),'lens','Net sales · Worked hours · Sales per worked hour'
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',11,
  jsonb_build_object(
    'type','table','status','complete','caption','Workforce sales · Last six months',
    'columns','[
      {"key":"worker","label":"Worker","type":"string"},
      {"key":"net_sales_ex_gst","label":"Net sales","type":"currency","currency":"AUD"},
      {"key":"worked_hours","label":"Worked hours","type":"number"},
      {"key":"sales_per_labour_hour","label":"Sales per worked hour","type":"currency","currency":"AUD"}
    ]'::jsonb,
    'rows','[{
      "worker":"Sam","net_sales_ex_gst":"15000.0000","worked_hours":"800.0000",
      "sales_per_labour_hour":"18.7500"
    }]'::jsonb,
    'resultId','semantic:'||repeat('b',64),
    'provenance',pg_temp.provenance(
      repeat('b',64),
      '[
        {"connector":"lightspeed","label":"Lightspeed","dataThrough":"2026-08-04T00:00:00Z"},
        {"connector":"deputy","label":"Deputy","dataThrough":"2026-08-04T00:00:00Z"}
      ]',
      '[
        {"metric":"commerce.net_sales_ex_gst","label":"Net sales","definition":"Governed net sales excluding GST."},
        {"metric":"workforce.worked_hours","label":"Worked hours","definition":"Governed actual worked hours."},
        {"metric":"composites.sales_per_labour_hour","label":"Sales per worked hour","definition":"Net sales divided by independently aggregated worked hours."}
      ]',
      'Last six months',:'performance_from'::timestamptz,:'performance_to'::timestamptz
    )
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',12,
  '{"type":"validation","status":"complete","name":"identity_attribution_coverage","outcome":"passed","detail":"Identity and attribution coverage passed."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',13,
  '{"type":"narrative","status":"complete","text":"Worker Sam had the highest governed net sales."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',14,
  jsonb_build_object(
    'type','chart','status','complete','caption','Net sales by worker','chartType','bar',
    'dataRef','semantic:'||repeat('b',64),'xKey','worker','yKey','net_sales_ex_gst'
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000632',
  '01K30000000000000000000634',15,
  jsonb_build_object(
    'type','answer','status','complete','state','Verified',
    'text','Worker Sam had the highest Net sales at AUD 15000.',
    'provenance',pg_temp.provenance(
      repeat('b',64),
      '[
        {"connector":"lightspeed","label":"Lightspeed","dataThrough":"2026-08-04T00:00:00Z"},
        {"connector":"deputy","label":"Deputy","dataThrough":"2026-08-04T00:00:00Z"}
      ]',
      '[
        {"metric":"commerce.net_sales_ex_gst","label":"Net sales","definition":"Governed net sales excluding GST."},
        {"metric":"workforce.worked_hours","label":"Worked hours","definition":"Governed actual worked hours."},
        {"metric":"composites.sales_per_labour_hour","label":"Sales per worked hour","definition":"Net sales divided by independently aggregated worked hours."}
      ]',
      'Last six months',:'performance_from'::timestamptz,:'performance_to'::timestamptz
    ),
    'followUps','[]'::jsonb,
    'claims','[{
      "statement":"Worker Sam had the highest Net sales at 15000.0000.",
      "assertion":"highest",
      "refs":[
        {"resultId":"semantic:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","rowIndex":0,"columnKey":"worker"},
        {"resultId":"semantic:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb","rowIndex":0,"columnKey":"net_sales_ex_gst"}
      ]
    }]'::jsonb
  )
);

SELECT * FROM control_plane.finalize_answer_artifact(
  '01K30000000000000000000630',
  '63000000-0000-4000-8000-000000000063'::uuid,
  '01K30000000000000000000632','01K30000000000000000000634',
  'resp_dogfood_m6_flagship','{"requests":2,"inputTokens":60,"outputTokens":20}',
  'verified','sha256:'||repeat('2',64),
  '{
    "rateCardId":"openai-2026.08.04","model":"gpt-5.6-sol","fastMode":true,
    "requests":2,"inputTokens":60,"cachedInputTokens":0,"cacheWriteInputTokens":0,
    "outputTokens":20,"estimatedCostUsdMicros":300,"pricingCompleteness":"request_level"
  }',
  jsonb_build_array(
    jsonb_build_object(
      'queryAuditId','01K30000000000000000000635','route','semantic',
      'topic','workforce_labour','bundleHash',repeat('a',64),'registryVersion','2026.08.04',
      'normalizedIr','{
        "kind":"single","topic":"workforce_labour","metrics":["rostered_hours"],
        "dimensions":["worker"],"filters":[],
        "time":{"field":"business_date","range":{"type":"today"},"compare":"none"},
        "sort":[{"metric":"rostered_hours","dir":"desc"}],"limit":50,"parameters":{}
      }'::jsonb,
      'compilerOutputHash',repeat('c',64),'resultDigest',:'roster_result_digest',
      'answerState','verified','validation','{"status":"passed","checks":[]}'::jsonb
    ),
    jsonb_build_object(
      'queryAuditId','01K30000000000000000000636','route','semantic',
      'topic','workforce_sales','bundleHash',repeat('b',64),'registryVersion','2026.08.04',
      'normalizedIr',replace(replace($performance_ir${
        "kind":"composite","topic":"workforce_sales","metrics":["sales_per_labour_hour"],
        "queries":[
          {
            "topic":"sales_performance","metrics":["net_sales_ex_gst"],
            "dimensions":["worker"],
            "filters":[{"field":"worker","op":"in","values":["01K20M8C4T4J25SB8RR4RG0SAM"]}],
            "time":{"field":"business_date","range":{"type":"absolute","from":"__FROM__","to":"__TO__"},"compare":"none"},
            "parameters":{}
          },
          {
            "topic":"workforce_labour","metrics":["worked_hours"],
            "dimensions":["worker"],
            "filters":[{"field":"worker","op":"in","values":["01K20M8C4T4J25SB8RR4RG0SAM"]}],
            "time":{"field":"business_date","range":{"type":"absolute","from":"__FROM__","to":"__TO__"},"compare":"none"},
            "parameters":{}
          }
        ],
        "alignOn":["worker"],"sort":[{"metric":"net_sales_ex_gst","dir":"desc"}],
        "limit":50,"parameters":{}
      }$performance_ir$,'__FROM__',:'performance_from'),'__TO__',:'performance_to')::jsonb,
      'compilerOutputHash',repeat('d',64),'resultDigest',:'performance_result_digest',
      'answerState','verified','validation','{"status":"passed","checks":[]}'::jsonb
    )
  )
) \gset flagship_

-- A second, independent conversation binds the exact category golden question
-- to its full month-to-date IR, table, chart and final cell references.
INSERT INTO control_plane.conversations(
  tenant_id,conversation_id,status,created_by
) VALUES (
  '01K30000000000000000000630','01K30000000000000000000637','active',
  '63000000-0000-4000-8000-000000000063'
);
INSERT INTO control_plane.conversation_turns(
  tenant_id,turn_id,conversation_id,turn_number,user_message,
  runtime_profile,status,created_by
) VALUES (
  '01K30000000000000000000630','01K30000000000000000000638',
  '01K30000000000000000000637',1,
  'Which categories are performing well this month?',
  '{"model":"gpt-5.6-sol","reasoningEffort":"high","fastMode":true,"runtime":"openai-agents-sdk"}',
  'running','63000000-0000-4000-8000-000000000063'
);
SELECT control_plane.dogfood_stable_json_sha256(jsonb_build_object(
  'columns','["product.category","net_sales_ex_gst"]'::jsonb,
  'rows','[{"product.category":"Bikes","net_sales_ex_gst":"84240.0000"}]'::jsonb
)) AS category_result_digest \gset
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',1,
  '{"type":"progress","status":"running","label":"Understanding the question"}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',2,
  '{"type":"narrative","status":"running","text":"I’m matching the question to Albert’s governed business definitions."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',3,
  '{"type":"narrative","status":"complete","text":"I checked that the connected sources can support this analysis before querying."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',4,
  '{"type":"progress","status":"running","label":"Running the governed analysis"}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',5,
  jsonb_build_object(
    'type','query','status','complete','topic','sales_performance',
    'metrics','["net_sales_ex_gst"]'::jsonb,
    'dimensions','["product.category"]'::jsonb,
    'timeRange',jsonb_build_object(
      'label','Month to date','start',:'category_start'::timestamptz,
      'end',:'category_end'::timestamptz,'timezone','Australia/Melbourne'
    ),'lens','Net sales'
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',6,
  jsonb_build_object(
    'type','table','status','complete','caption','Sales performance · Month to date',
    'columns','[
      {"key":"product.category","label":"Product category","type":"string"},
      {"key":"net_sales_ex_gst","label":"Net sales","type":"currency","currency":"AUD"}
    ]'::jsonb,
    'rows','[{"product.category":"Bikes","net_sales_ex_gst":"84240.0000"}]'::jsonb,
    'resultId','semantic:'||repeat('e',64),
    'provenance',pg_temp.provenance(
      repeat('e',64),
      '[{"connector":"lightspeed","label":"Lightspeed","dataThrough":"2026-08-04T00:00:00+10:00"}]',
      '[{"metric":"commerce.net_sales_ex_gst","label":"Net sales","definition":"Governed net sales excluding GST."}]',
      'Month to date',:'category_start'::timestamptz,:'category_end'::timestamptz
    )
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',7,
  '{"type":"validation","status":"complete","name":"line_maths","outcome":"passed","detail":"Line maths passed."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',8,
  '{"type":"narrative","status":"complete","text":"Bikes is the highest governed category by net sales."}'
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',9,
  jsonb_build_object(
    'type','chart','status','complete','caption','Net sales by category','chartType','bar',
    'dataRef','semantic:'||repeat('e',64),'xKey','product.category','yKey','net_sales_ex_gst'
  )
);
SELECT pg_temp.append_event(
  '01K30000000000000000000630','01K30000000000000000000637',
  '01K30000000000000000000638',10,
  jsonb_build_object(
    'type','answer','status','complete','state','Verified',
    'text','Product category Bikes had the highest Net sales at AUD 84240.',
    'provenance',pg_temp.provenance(
      repeat('e',64),
      '[{"connector":"lightspeed","label":"Lightspeed","dataThrough":"2026-08-04T00:00:00+10:00"}]',
      '[{"metric":"commerce.net_sales_ex_gst","label":"Net sales","definition":"Governed net sales excluding GST."}]',
      'Month to date',:'category_start'::timestamptz,:'category_end'::timestamptz
    ),
    'followUps','[]'::jsonb,
    'claims',jsonb_build_array(jsonb_build_object(
      'statement','Product category Bikes had the highest Net sales at 84240.0000.',
      'assertion','highest','refs',jsonb_build_array(
        jsonb_build_object(
          'resultId','semantic:'||repeat('e',64),'rowIndex',0,'columnKey','product.category'
        ),
        jsonb_build_object(
          'resultId','semantic:'||repeat('e',64),'rowIndex',0,'columnKey','net_sales_ex_gst'
        )
      )
    ))
  )
);

SELECT * FROM control_plane.finalize_answer_artifact(
  '01K30000000000000000000630',
  '63000000-0000-4000-8000-000000000063'::uuid,
  '01K30000000000000000000637','01K30000000000000000000638',
  'resp_dogfood_m6_category','{"requests":1,"inputTokens":30,"outputTokens":10}',
  'verified','sha256:'||repeat('3',64),
  '{
    "rateCardId":"openai-2026.08.04","model":"gpt-5.6-sol","fastMode":true,
    "requests":1,"inputTokens":30,"cachedInputTokens":0,"cacheWriteInputTokens":0,
    "outputTokens":10,"estimatedCostUsdMicros":150,"pricingCompleteness":"request_level"
  }',
  jsonb_build_array(jsonb_build_object(
    'queryAuditId','01K30000000000000000000639','route','semantic',
    'topic','sales_performance','bundleHash',repeat('e',64),'registryVersion','2026.08.04',
    'normalizedIr','{
      "kind":"single","topic":"sales_performance","metrics":["net_sales_ex_gst"],
      "dimensions":["product.category"],"filters":[],
      "time":{"field":"business_date","range":{"type":"month_to_date"},"compare":"none"},
      "sort":[{"metric":"net_sales_ex_gst","dir":"desc"}],"limit":20,
      "parameters":{"category_mode":"as_currently_classified"}
    }'::jsonb,
    'compilerOutputHash',repeat('f',64),'resultDigest',:'category_result_digest',
    'answerState','verified','validation','{"status":"passed","checks":[]}'::jsonb
  ))
) \gset category_

SELECT control_plane.dogfood_answer_artifact_evidence(
  '01K30000000000000000000630',:'flagship_answer_artifact_id',
  'flagship','sales_performance',:'m6_barrier'
) AS flagship_evidence \gset
SELECT control_plane.dogfood_answer_artifact_evidence(
  '01K30000000000000000000630',:'category_answer_artifact_id',
  'category','sales_performance',:'m6_barrier'
) AS category_evidence \gset

SELECT pg_temp.assert_true(
  (:'flagship_evidence'::jsonb->>'queryCount')::integer=2
  AND :'flagship_evidence'::jsonb->>'contractVersion'='1'
  AND :'flagship_evidence'::jsonb->>'lineageBindingDigest'~'^[a-f0-9]{64}$'
  AND :'flagship_evidence'::jsonb->>'questionDigest'~'^[a-f0-9]{64}$'
  AND :'flagship_evidence'::jsonb->>'semanticPlanDigest'~'^[a-f0-9]{64}$',
  'flagship evidence must bind its clarification, exact IR, query hashes and trace'
);
SELECT pg_temp.assert_true(
  (:'category_evidence'::jsonb->>'queryCount')::integer=1
  AND (:'category_evidence'::jsonb->>'chartPresent')::boolean
  AND :'category_evidence'::jsonb->>'caseContractDigest'=
      (SELECT contract_digest
         FROM control_plane.protected_dogfood_answer_case_contracts
        WHERE case_key='category')
  AND :'category_evidence'::jsonb->>'provenanceDigest'~'^[a-f0-9]{64}$'
  AND :'category_evidence'::jsonb->>'traceContractDigest'~'^[a-f0-9]{64}$',
  'category evidence must bind the exact golden question, MTD table, chart and provenance'
);
SELECT pg_temp.assert_true(
  (SELECT count(*)=2 AND bool_and(
     contract_digest=control_plane.dogfood_evidence_sha256(contract)
   ) FROM control_plane.protected_dogfood_answer_case_contracts),
  'the database must own exactly two content-addressed M6 case contracts'
);
SELECT pg_temp.assert_true(
  NOT has_table_privilege(
    'albert_operator_diagnostic_control',
    'control_plane.protected_dogfood_answer_case_contracts','SELECT'
  ) AND NOT has_function_privilege(
    'albert_operator_diagnostic_control',
    'control_plane.dogfood_answer_artifact_evidence(text,text,text,text,timestamptz)',
    'EXECUTE'
  ),
  'the collector must reach M6 validation only through the fixed capture function'
);

SELECT set_config('test.category_answer_artifact_id',:'category_answer_artifact_id',true);
SELECT set_config('test.m6_barrier',:'m6_barrier',true);

DO $$
BEGIN
  PERFORM control_plane.dogfood_answer_artifact_evidence(
    '01K30000000000000000000630',current_setting('test.category_answer_artifact_id'),
    'category','sales',current_setting('test.m6_barrier')::timestamptz
  );
  RAISE EXCEPTION 'an unreviewed category Topic was accepted';
EXCEPTION WHEN SQLSTATE '22023' THEN NULL;
END;
$$;

DO $$
BEGIN
  PERFORM control_plane.dogfood_answer_artifact_evidence(
    '01K30000000000000000000630',current_setting('test.category_answer_artifact_id'),
    'flagship','sales_performance',current_setting('test.m6_barrier')::timestamptz
  );
  RAISE EXCEPTION 'the category artefact was accepted as the flagship flow';
EXCEPTION WHEN SQLSTATE '55000' THEN NULL;
END;
$$;

ROLLBACK;
