primary_region = "syd"

[build]
  image = "flyio/fly-autoscaler@sha256:8befadf6269dd637e3f3759f61039bd8e1543e9ec3d06523e974e76a80c207df"

[env]
  FAS_PROMETHEUS_METRIC_NAME = "queue_pressure"
  FAS_PROMETHEUS_QUERY = "max(albert_sync_queue_depth{app='$APP_NAME'}) / 32 + max(albert_sync_queue_oldest_age_seconds{app='$APP_NAME'}) / 300"
  FAS_CREATED_MACHINE_COUNT = "min(40, 2 + queue_pressure)"

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
